SensorSuite-Types DEFINITIONS ::=
BEGIN
IMPORTS T-Int32, T-UInt32, T-Int8, T-UInt8, T-Boolean FROM TASTE-BasicTypes
T-Int64, T-UInt16, T-Double, T-Float, T-UInt64, T-String FROM TASTE-ExtendedTypes
Time FROM Time-Types
Vector2d, Vector3d, Quaterniond FROM Eigen-Types
Temperature FROM Temperature-Types
Point FROM Point-Types;

--  State of operation for sensors and corresponding commands.
SensorState  ::=  ENUMERATED {inactive, standby, operational, failure}
StateCommand ::= ENUMERATED { activate, start, stop, deactivate}

-- Sensor rate given as seconds between periodic samples (inverse of frequency).
SensorRate ::= REAL(0.0 .. 3.402823466e+38)

--  Sensor status messages.
SensorStatus ::= SEQUENCE{
    timestamp Time,
    device-state SensorState,
    device-temperature Temperature,
    debug-message T-String
}

--- Sample attribute
Attribute-value-t ::=
CHOICE
{
   boolean-value        T-Boolean,
   discrete-value       T-Int64,
   real-value           T-Double,
   string-value         T-String
}

Sample-attribute-t ::=
SEQUENCE
{
    attribute-name      T-String,
    attribute-value     Attribute-value-t
}

--- Definition of frame modes from SARGON
Frame-mode-t ::= ENUMERATED
{
     mode-undefined,
     mode-grayscale,
     mode-rgb,
     mode-uyvy,
     mode-bgr,
     mode-rgb32,
     raw-modes,
     mode-bayer,
     mode-bayer-rggb,
     mode-bayer-grbg,
     mode-bayer-bggr,
     mode-bayer-gbrg,
     compressed-modes,
     mode-pjpg,
     mode-jpeg,
     mode-png
}

--- Definition of frame status from SARGON.
Frame-status-t ::= ENUMERATED
{
     status-empty,
     status-valid,
     status-invalid
}

--- Definition from SARGON.
Frame-size-t   ::=
SEQUENCE
{
    width               T-UInt16,
    height              T-UInt16
}

--- Modified generic frame definition from SARGON.
Frame{T-Uint32: maxBytes, T-Uint16: maxAttributes}   ::=
SEQUENCE
{
    timestamp           Time,
    image               OCTET STRING (SIZE(0..maxBytes)),
    attributes          SEQUENCE (SIZE(0..maxAttributes)) OF Sample-attribute-t,
    datasize            Frame-size-t,
    data-depth          T-UInt32,
    pixel-size          T-UInt32,
    row-size            T-UInt32,
    frame-mode          Frame-mode-t,
    frame-status        Frame-status-t
}

--- Modified generic point-cloud definition from SARGON.
Pointcloud{T-Uint32: maxPointCloudSize, T-Uint16: maxAttributes}   ::=
SEQUENCE
{
    timestamp           Time,
    points              SEQUENCE (SIZE(1..maxPointcloudSize)) OF Point,
    attributes          SEQUENCE (SIZE(0..maxAttributes)) OF Sample-attribute-t
}

--- Camera command
ExposureTime            ::= REAL(1.0e-9 .. 1.0e9)
SensorGain              ::= REAL(1.0 .. 1.0e6)
FlashStrength           ::= REAL(0.0 .. 1.0)
IlluminationPattern     ::= INTEGER(0..255)

CameraCommand ::= CHOICE{
    set-state                           StateCommand,
    set-rate                            SensorRate,
    set-exposure                        ExposureTime,
    set-gain                            SensorGain,
    set-auto-exposure                   BOOLEAN,
    set-exposure-limit                  ExposureTime,
    set-gain-limit                      SensorGain,
    activate-flash-illumination         BOOLEAN,
    set-flash-strength                  FlashStrength,
    activate-pattern-illumination       BOOLEAN,
    set-illumination-pattern            IlluminationPattern,
    trigger                             T-Boolean
}

END
