--------------------------------------------------------------------------------
--- ASN.1 message definitions for the I3DS sensor suite.
---
--- Copyright (C) 2017      Stiftelsen SINTEF
--- Copyright (C) 2018      SINTEF AS
---
--- This program is free software; you can redistribute it and/or
--- modify it under the terms of the GNU General Public License
--- as published by the Free Software Foundation; either version 2
--- of the License, or (at your option) any later version.
---
--- This program is distributed in the hope that it will be useful,
--- but WITHOUT ANY WARRANTY; without even the implied warranty of
--- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--- GNU General Public License for more details.
---
--- You should have received a copy of the GNU General Public License
--- along with this program;  if not, see <http://www.gnu.org/licenses/>.
--------------------------------------------------------------------------------

Analog-Types DEFINITIONS ::=
BEGIN
IMPORTS SensorCommand, SensorConfiguration FROM SensorSuite-Types
T-UInt32, T-Boolean FROM TASTE-BasicTypes
T-Float, T-String FROM TASTE-ExtendedTypes
Time FROM Time-Types;

--- Analog sensor command
AnalogCommand ::=
CHOICE
{
   sensor-command   SensorCommand,
   set-batch-count  T-UInt32
}

--- Analog sensor configuration.
AnalogConfiguration ::=
SEQUENCE
{
   config-sensor       SensorConfiguration,
   config-batch-count  T-UInt32
}

--- Analog measurement
AnalogMeasurement{T-UInt32: maxSamples} ::=
SEQUENCE
{
   timestamp   Time,
   samples     SEQUENCE (SIZE(1..maxSamples)) OF T-Float
}

END
