Analog-Types DEFINITIONS ::=
BEGIN
IMPORTS StateCommand, SensorState, SensorRate FROM SensorSuite-Types
T-UInt32, T-Boolean FROM TASTE-BasicTypes
T-UInt16, T-Float, T-String FROM TASTE-ExtendedTypes
Time FROM Time-Types;

--- Sample mode
SampleMode-t ::=
ENUMERATED
{
   sample-mode-batch,
   sample-mode-trigger-up,
   sample-mode-trigger-down,
   sample-mode-trigger-any
}

--- Sample trigger
SampleTrigger-t ::=
ENUMERATED
{
   sample-trigger-time,
   sample-trigger-up,
   sample-trigger-down
}

--- Analog config request
AnalogConfigRequest ::=
CHOICE
{
   command             StateCommand,
   set-rate            SensorRate,
   set-mode            SampleMode-t,
   set-batch-size      T-UInt16,
   set-trigger-level   T-Float
}

--- Analog config response
AnalogConfigResponse ::=
SEQUENCE
{
   success                T-Boolean,
   error-message          T-String,
   sensor-state           SensorState,
   config-rate            SensorRate,
   config-mode            SampleMode-t,
   config-batch-size      T-UInt16,
   config-trigger-level   T-Float
}

--- Analog measurement
AnalogMeasurement{T-UInt16: maxSamples} ::=
SEQUENCE
{
   timestamp   Time,
   samples     SEQUENCE (SIZE(1..maxSamples)) OF T-Float,
   trigger     SampleTrigger-t
}

END
