--------------------------------------------------------------------------------
--- ASN.1 message definitions for the I3DS sensor suite.
---
--- Copyright (C) 2017      Stiftelsen SINTEF
---
--- This program is free software; you can redistribute it and/or
--- modify it under the terms of the GNU General Public License
--- as published by the Free Software Foundation; either version 2
--- of the License, or (at your option) any later version.
---
--- This program is distributed in the hope that it will be useful,
--- but WITHOUT ANY WARRANTY; without even the implied warranty of
--- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--- GNU General Public License for more details.
---
--- You should have received a copy of the GNU General Public License
--- along with this program;  if not, see <http://www.gnu.org/licenses/>.
--------------------------------------------------------------------------------

Camera-Types DEFINITIONS ::=
BEGIN
IMPORTS StateCommand, SensorState, SensorRate FROM SensorSuite-Types
SampleValidity, SampleAttributeList FROM SampleAttribute-Types
PlanarRegion FROM Region-Types
T-UInt8, T-UInt32, T-Boolean FROM TASTE-BasicTypes
T-UInt16, T-String FROM TASTE-ExtendedTypes
Frame-mode-t, ImageFrame FROM Frame-Types
Time FROM Time-Types;

--- Exposure time in seconds
ExposureTime ::= REAL(1.0e-9 .. 1.0e12)

--- Camera sensor gain, max value depends on sensor
SensorGain ::= REAL(1.0 .. 1.0e6)

--- Flash strength if supported, range from 0 (off) to 1 (full)
FlashStrength ::= REAL(0.0 .. 1.0)

--- Illumination pattern if supported, 0 is none, range depends on camera
IlluminationPattern ::= T-UInt16

--- Camera config request
CameraConfigRequest ::=
CHOICE
{
    command                    StateCommand,
    trigger                    T-Boolean,
    set-rate                   SensorRate,
    set-exposure               ExposureTime,
    set-gain                   SensorGain,
    set-auto-exposure          T-Boolean,
    set-exposure-limit         ExposureTime,
    set-gain-limit             SensorGain,
    set-region                 PlanarRegion,
    set-flash-illumination     T-Boolean,
    set-flash-strength         FlashStrength,
    set-pattern-illumination   T-Boolean,
    set-illumination-pattern   IlluminationPattern
}

--- Camera config response
CameraConfigResponse ::=
SEQUENCE
{
   success                       T-Boolean,
   error-message                 T-String,
   sensor-state                  SensorState,
   config-rate                   SensorRate,
   config-exposure               ExposureTime,
   config-gain                   SensorGain,
   config-auto-exposure          T-Boolean,
   config-exposure-limit         ExposureTime,
   config-gain-limit             SensorGain,
   config-region                 PlanarRegion,
   config-flash-illumination     T-Boolean,
   config-flash-strength         FlashStrength,
   config-pattern-illumination   T-Boolean,
   config-illumination-pattern   IlluminationPattern
}

--- Camera measurement
CameraMeasurement{T-UInt32: maxImageBytes, T-UInt32: maxAttributes} ::=
SEQUENCE
{
   timestamp      Time,
   image          ImageFrame{maxImageBytes},
   frame-mode     Frame-mode-t,
   region         PlanarRegion,
   data-depth     T-UInt8,
   pixel-size     T-UInt8,
   attributes     SampleAttributeList{maxAttributes},
   validity       SampleValidity
}

--- Stereo camera measurement
StereoCameraMeasurement{T-UInt32: maxImageBytes, T-UInt32: maxAttributes} ::=
SEQUENCE
{
   timestamp      Time,
   image-left     ImageFrame{maxImageBytes},
   image-right    ImageFrame{maxImageBytes},
   frame-mode     Frame-mode-t,
   region         PlanarRegion,
   data-depth     T-UInt8,
   pixel-size     T-UInt8,
   attributes     SampleAttributeList{maxAttributes},
   validity       SampleValidity
}

END
