Camera-Types DEFINITIONS ::=
BEGIN
IMPORTS StateCommand, SensorState, SensorRate, ROI-t FROM SensorSuite-Types
T-Boolean FROM TASTE-BasicTypes
T-UInt16, T-String FROM TASTE-ExtendedTypes
Frame FROM Frame-Types;

--- Exposure time in seconds
ExposureTime ::= REAL(1.0e-9 .. 1.0e12)

--- Camera sensor gain, max value depends on sensor
SensorGain ::= REAL(1.0 .. 1.0e6)

--- Flash strength if supported, range from 0 (off) to 1 (full)
FlashStrength ::= REAL(0.0 .. 1.0)

--- Illumination pattern if supported, 0 is none, range depends on camera
IlluminationPattern ::= T-UInt16

--- Camera config request
CameraConfigRequest ::=
CHOICE
{
    command                    StateCommand,
    trigger                    T-Boolean,
    set-rate                   SensorRate,
    set-exposure               ExposureTime,
    set-gain                   SensorGain,
    set-auto-exposure          T-Boolean,
    set-exposure-limit         ExposureTime,
    set-gain-limit             SensorGain,
    set-roi                    ROI-t,
    set-flash-illumination     T-Boolean,
    set-flash-strength         FlashStrength,
    set-pattern-illumination   T-Boolean,
    set-illumination-pattern   IlluminationPattern
}

--- Camera config response
CameraConfigResponse ::=
SEQUENCE
{
   success                       T-Boolean,
   error-message                 T-String,
   sensor-state                  SensorState,
   config-rate                   SensorRate,
   config-exposure               ExposureTime,
   config-gain                   SensorGain,
   config-auto-exposure          T-Boolean,
   config-exposure-limit         ExposureTime,
   config-gain-limit             SensorGain,
   config-roi                    ROI-t,
   config-flash-illumination     T-Boolean,
   config-flash-strength         FlashStrength,
   config-pattern-illumination   T-Boolean,
   config-illumination-pattern   IlluminationPattern
}

--- Camera measurement
CameraMeasurement{T-Uint32: maxImageBytes, T-Uint16: maxAttributes} ::=
SEQUENCE
{
    timestamp    Time,
    image        Frame{maxImageBytes},
    attributes   SEQUENCE (SIZE(0..maxAttributes)) OF Sample-attribute-t,
    roi          ROI-t
}

--- Stereo camera measurement
StereoCameraMeasurement{T-Uint32: maxImageBytes, T-Uint16: maxAttributes} ::=
SEQUENCE
{
    timestamp     Time,
    image-left    Frame{maxImageBytes},
    image-right   Frame{maxImageBytes},
    attributes    SEQUENCE (SIZE(0..maxAttributes)) OF Sample-attribute-t,
    roi           ROI-t
}

END
