DepthMap-Types DEFINITIONS ::=
BEGIN
IMPORTS T-UInt32 FROM TASTE-BasicTypes
T-UInt16, T-Float FROM TASTE-ExtendedTypes;

--- Depth measurement validity adapted from SARGON.
Depth-validity-t ::=
ENUMERATED
{
   valid-measurement,
   too-far,
   too-near,
   measurement-error
}

--- List of depth measurement validities.
DepthValidityList{T-UInt32: maxSize} ::= SEQUENCE (SIZE(1..maxSize)) OF Depth-validity-t

--- Depth map with distances in meters relative to sensor.
DepthMap{T-UInt32: maxSize} ::= SEQUENCE (SIZE(1..maxSize)) OF T-Float

END
