Frame-Types DEFINITIONS ::=
BEGIN
IMPORTS T-UInt32 FROM TASTE-BasicTypes
T-UInt16 FROM TASTE-ExtendedTypes;

--- Legal frame modes adapted from SARGON
Frame-mode-t ::=
ENUMERATED
{
     mode-undefined,
     mode-mono, -- Grayscale image
     mode-rgb, -- Colour image in RGB format
     mode-bgr, -- Colour image in BGR format
     mode-uyvy, -- Colour image in UYVY format
     mode-rgba, -- Colour image in RGBA format (RGB32)
     mode-bayer-rggb, -- RAW image with RGGB bayer layout
     mode-bayer-grbg, -- RAW image with GRBG bayer layout
     mode-bayer-bggr, -- RAW image with BGGR bayer layout
     mode-bayer-gbrg, -- RAW image with GBRG bayer layout
     mode-pjpg, -- Compressed image in PJPG format
     mode-jpeg, -- Compressed image in JPEG format
     mode-png, -- Compressed image in PNG format
     mode-tiff -- Image in TIFF format
}

--- Image frame is an octet string
ImageFrame{T-UInt32: maxImageBytes} ::= OCTET STRING (SIZE(0..maxImageBytes))

END
