IMU-Types DEFINITIONS ::=
BEGIN
IMPORTS StateCommand, SensorState, SensorRate FROM SensorSuite-Types
Time FROM Time-Types
Vector3d FROM Eigen-Types
T-Boolean FROM TASTE-BasicTypes
T-String FROM TASTE-ExtendedTypes;

--- IMU config request
IMUConfigRequest ::=
CHOICE
{
   command    StateCommand,
   set-rate   SensorRate
}

--- IMU config response
IMUConfiguration ::=
SEQUENCE
{
   success         T-Boolean,
   error-message   T-String,
   sensor-state    SensorState,
   config-rate     SensorRate
}

--- IMU measurement definition
IMUMeasurement ::=
SEQUENCE
{
   timestamp      Time,
   linear-accel   Vector3d,
   angular-rate   Vector3d
}

END
