LIDAR-Types DEFINITIONS ::=
BEGIN
IMPORTS StateCommand, SensorState, SensorRate, ROI-t FROM SensorSuite-Types
PointCloud FROM PointCloud-Types
T-Boolean FROM TASTE-BasicTypes
T-String FROM TASTE-ExtendedTypes;

--- LIDAR config request
LIDARConfigRequest ::=
CHOICE
{
   command   StateCommand,
   trigger   T-Boolean,
   set-rate  SensorRate,
   set-roi   ROI-t
}

--- LIDAR config response
LIDARConfigResponse ::=
SEQUENCE
{
   success         T-Boolean,
   error-message   T-String,
   sensor-state    SensorState,
   config-rate     SensorRate,
   config-roi      ROI-t
}

--- LIDAR measurement
LIDARMeasurement{T-Uint32: maxPointCloudSize, T-Uint16: maxAttributes} ::=
SEQUENCE
{
    timestamp  Time,
    points     PointCloud{maxPointCloudSize},
    attributes SEQUENCE (SIZE(0..maxAttributes)) OF Sample-attribute-t,
    roi        ROI-t
}

END
