PointCloud-Types DEFINITIONS ::=
BEGIN
IMPORTS Point FROM Point-Types;

--- Point-cloud in meters relative to sensor.
PointCloud{T-Uint32: maxPointCloudSize} ::=
SEQUENCE
{
    points   SEQUENCE (SIZE(1..maxPointCloudSize)) OF Point,
    size     T-Uint32
}

END
