PointCloud-Types DEFINITIONS ::=
BEGIN
IMPORTS T-UInt32 FROM TASTE-BasicTypes
Point FROM Point-Types;

--- Point-cloud in meters relative to sensor right-hand XYZ
PointCloud{T-UInt32: maxPointCloudSize} ::= SEQUENCE (SIZE(1..maxPointCloudSize)) OF Point

END
