--------------------------------------------------------------------------------
--- ASN.1 message definitions for the I3DS sensor suite.
---
--- Copyright (C) 2017      Stiftelsen SINTEF
---
--- This program is free software; you can redistribute it and/or
--- modify it under the terms of the GNU General Public License
--- as published by the Free Software Foundation; either version 2
--- of the License, or (at your option) any later version.
---
--- This program is distributed in the hope that it will be useful,
--- but WITHOUT ANY WARRANTY; without even the implied warranty of
--- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--- GNU General Public License for more details.
---
--- You should have received a copy of the GNU General Public License
--- along with this program;  if not, see <http://www.gnu.org/licenses/>.
--------------------------------------------------------------------------------

Radar-Types DEFINITIONS ::=
BEGIN
IMPORTS StateCommand, SensorState, SensorRate FROM SensorSuite-Types
SampleValidity, SampleAttributeList FROM SampleAttribute-Types
PlanarRegion FROM Region-Types
T-UInt32, T-Boolean FROM TASTE-BasicTypes
T-UInt16, T-String FROM TASTE-ExtendedTypes
DepthMap, DepthValidityList FROM DepthMap-Types
Time FROM Time-Types;

--- Radar config request
RadarConfigRequest ::=
CHOICE
{
   command     StateCommand,
   trigger     T-Boolean,
   set-rate    SensorRate,
   set-region  PlanarRegion
}

--- Radar config response
RadarConfigResponse ::=
SEQUENCE
{
   success         T-Boolean,
   error-message   T-String,
   sensor-state    SensorState,
   config-rate     SensorRate,
   config-region   PlanarRegion
}

--- Radar measurement
RadarMeasurement{T-UInt32: maxDepthMapSize, T-UInt32: maxAttributes} ::=
SEQUENCE
{
    timestamp        Time,
    distances        DepthMap{maxDepthMapSize},
    depth-validity   DepthValidityList{maxDepthMapSize},
    region           PlanarRegion,
    attributes       SampleAttributeList{maxAttributes},
    validity         SampleValidity
}

END
