Radar-Types DEFINITIONS ::=
BEGIN
IMPORTS StateCommand, SensorState, SensorRate, ROI-t FROM SensorSuite-Types
T-Boolean FROM TASTE-BasicTypes
T-String FROM TASTE-ExtendedTypes;

--- Radar config request
RadarConfigRequest ::=
CHOICE
{
   command    StateCommand,
   trigger    T-Boolean,
   set-rate   SensorRate,
   set-roi    ROI-t
}

--- Radar config response
RadarConfigResponse ::=
SEQUENCE
{
   success         T-Boolean,
   error-message   T-String,
   sensor-state    SensorState,
   config-rate     SensorRate,
   config-roi      ROI-t
}

--- Radar measurement
RadarMeasurement{T-Uint32: maxDepthMapSize, T-Uint16: maxAttributes} ::=
SEQUENCE
{
    timestamp  Time,
    depth      DepthMap{maxDepthMapSize},
    attributes SEQUENCE (SIZE(0..maxAttributes)) OF Sample-attribute-t,
    roi        ROI-t
}

END
