--------------------------------------------------------------------------------
--- ASN.1 message definitions for the I3DS sensor suite.
---
--- Copyright (C) 2017      Stiftelsen SINTEF
---
--- This program is free software; you can redistribute it and/or
--- modify it under the terms of the GNU General Public License
--- as published by the Free Software Foundation; either version 2
--- of the License, or (at your option) any later version.
---
--- This program is distributed in the hope that it will be useful,
--- but WITHOUT ANY WARRANTY; without even the implied warranty of
--- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--- GNU General Public License for more details.
---
--- You should have received a copy of the GNU General Public License
--- along with this program;  if not, see <http://www.gnu.org/licenses/>.
--------------------------------------------------------------------------------

SampleAttribute-Types DEFINITIONS ::=
BEGIN
IMPORTS T-Boolean FROM TASTE-BasicTypes
T-Int64, T-Int16, T-UInt16, T-Double, T-String FROM TASTE-ExtendedTypes
Time FROM Time-Types
Temperature FROM Temperature-Types;

--- Sample validity
SampleValidity ::= ENUMERATED
{
     sample-empty,
     sample-valid,
     sample-invalid
}

--- Short string for keys
Attribute-key-t ::= OCTET STRING (SIZE(0..16))

--- Sample attribute value
Attribute-value-t ::=
CHOICE
{
   boolean-value    T-Boolean,
   discrete-value   T-Int64,
   real-value       T-Double,
   string-value     T-String
}

--- Sample attribute name/value pair
Sample-attribute-t ::=
SEQUENCE
{
    attribute-key     Attribute-key-t,
    attribute-value   Attribute-value-t
}

--- Sample attribute list
SampleAttributeList{T-UInt32: maxSize} ::= SEQUENCE (SIZE(1..maxSize)) OF Sample-attribute-t

END
