ToFCamera-Types DEFINITIONS ::=
BEGIN
IMPORTS StateCommand, SensorState, SensorRate FROM SensorSuite-Types
SampleValidity, SampleAttributeList FROM SampleAttribute-Types
PlanarRegion FROM Region-Types
DepthValidityList, DepthMap FROM DepthMap-Types
T-UInt32, T-Boolean FROM TASTE-BasicTypes
T-String FROM TASTE-ExtendedTypes
Time FROM Time-Types;

--- ToF config request
ToFConfigRequest ::=
CHOICE
{
   command      StateCommand,
   trigger      T-Boolean,
   set-rate     SensorRate,
   set-region   PlanarRegion
}

--- ToF config response
ToFConfigResponse ::=
CHOICE
{
   success         T-Boolean,
   error-message   T-String,
   sensor-state    SensorState,
   config-rate     SensorRate,
   config-region   PlanarRegion
}

--- ToF measurement
ToFMeasurement{T-UInt32: maxDepthMapSize, T-UInt32: maxAttributes} ::=
SEQUENCE
{
    timestamp        Time,
    distances        DepthMap{maxDepthMapSize},
    depth-validity   DepthValidityList{maxDepthMapSize},
    region           PlanarRegion,
    attributes       SampleAttributeList{maxAttributes},
    validity         SampleValidity
}

END
