ToFCamera-Types DEFINITIONS ::=
BEGIN
IMPORTS StateCommand, SensorState, SensorRate, ROI-t FROM SensorSuite-Types
PointCloud FROM PointCloud-Types
T-Boolean FROM TASTE-BasicTypes
T-String FROM TASTE-ExtendedTypes;

--- ToF config request
ToFConfigRequest ::=
CHOICE
{
   command   StateCommand,
   trigger   T-Boolean,
   set-rate  SensorRate,
   set-roi   ROI-t
}

--- ToF config response
ToFConfigResponse ::=
CHOICE
{
   success         T-Boolean,
   error-message   T-String,
   sensor-state    SensorState,
   config-rate     SensorRate,
   config-roi      ROI-t
}

--- ToF measurement
ToFMeasurement{T-Uint32: maxPointCloudSize, T-Uint16: maxAttributes} ::=
SEQUENCE
{
    timestamp    Time,
    points       PointCloud{maxPointCloudSize},
    attributes   SEQUENCE (SIZE(0..maxAttributes)) OF Sample-attribute-t,
    roi          ROI-t
}

END
