Basler-HRCamera-Types DEFINITIONS ::=
BEGIN
IMPORTS CameraMeasurement FROM Camera-Types
T-UInt32 FROM TASTE-BasicTypes
T-UInt16 FROM TASTE-ExtendedTypes;

--- Basler HR camera is 16 bits * 2048 * 2048 = 8388608 Bytes = 8 MiB
basler-HRImageWidth  T-UInt16 ::= 2048
basler-HRImageHeight T-UInt16 ::= 2048
basler-HRDataDepth   T-UInt16 ::= 12
basler-HRPixelSize   T-UInt16 ::= 2
basler-HRImageSize   T-UInt32 ::= 8388608

--- Basler HR camera measurement
Basler-HRCameraMeasurement ::= CameraMeasurement{basler-HRImageSize, 3}

END
