# Locate and configure the ASN1CC compiler
#
# The following variables can be set and are optional:
#
# ``ASN_OUTPUT_DIR``
#   Folder to output generated files in. Will use current binary
#   dir if varibale is not set.
#
# Example:
#
# .. code-block:: cmake
#
#   find_package(Asn REQUIRED)
#   include_directories(${ASN_INCLUDE_DIRS})
#   include_directories(${CMAKE_CURRENT_BINARY_DIR})
#   asn_generate_cpp(ASN_SRCS ASN_HDRS foo.asn)
#   asn_generate_python(ASN_PY foo.asn)
#   add_executable(bar bar.cc ${ASN_SRCS} ${ASN_HDRS})
#   target_link_libraries(bar ${ASN_LIBRARIES})
#
# .. note::
#   The ``asn_generate_cpp`` and ``asn_generate_python``
#   functions and :command:`add_executable` or :command:`add_library`
#   calls only work properly within the same directory.
#
# .. command:: asn_generate_cpp
#
#   Add custom commands to process ``.asn`` files to C++::
#
#     asn_generate_cpp (<SRCS> <HDRS> [<ARGN>...])
#
#   ``SRCS``
#     Variable to define with autogenerated source files
#   ``HDRS``
#     Variable to define with autogenerated header files
#   ``ARGN``
#     ``.asn`` files
#
# .. command:: asn_generate_python
#
#   Add custom commands to process ``.asn`` files to Python::
#
#     asn_generate_python (<PY> [<ARGN>...])
#
#   ``PY``
#     Variable to define with autogenerated Python files
#   ``ARGN``
#     ``.asn`` filess

#=============================================================================
# Copyright 2009 Kitware, Inc.
# Copyright 2009-2011 Philip Lowman <philip@yhbt.com>
# Copyright 2008 Esben Mose Hansen, Ange Optimization ApS
#
# Distributed under the OSI-approved BSD License (the "License");
# see accompanying file Copyright.txt for details.
#
# This software is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the License for more information.
#=============================================================================
# (To distribute this file outside of CMake, substitute the full
#  License text for the above reference.)

function(ASN1CC_GENERATE_C SRCS HDRS ASN_OUTPUT_DIR)
  if(NOT ARGN)
    message(SEND_ERROR "Error: ASN1CC_GENERATE_C() called without any ASN.1 files")
    return()
  endif()

  set (_asn1cc_files)

  # Create an include path for each file specified
  foreach(FIL ${ARGN})
    get_filename_component(ABS_FIL ${FIL} ABSOLUTE)
    list(FIND _asn1cc_files ${ABS_FIL} _contains_already)
    if(${_contains_already} EQUAL -1)
      list(APPEND _asn1cc_files ${ABS_FIL})
    endif()
  endforeach()

  set(${SRCS}
    "${ASN_OUTPUT_DIR}/asn1crt.c"
    "${ASN_OUTPUT_DIR}/acn.c"
    "${ASN_OUTPUT_DIR}/real.c")

  set(${HDRS}
    "${ASN_OUTPUT_DIR}/asn1crt.h")

  foreach(FIL ${_asn1cc_files})
    get_filename_component(ABS_FIL ${FIL} ABSOLUTE)
    get_filename_component(FIL_WE ${FIL} NAME_WE)

    list(APPEND ${SRCS} "${ASN_OUTPUT_DIR}/${FIL_WE}.c")
    list(APPEND ${HDRS} "${ASN_OUTPUT_DIR}/${FIL_WE}.h")

  endforeach()

  add_custom_command(
    OUTPUT "${ASN_OUTPUT_DIR}/asn1crt.c"
    "${ASN_OUTPUT_DIR}/asn1crt.h"
    COMMAND mkdir -p ${ASN_OUTPUT_DIR}
    COMMAND ${ASN1CC_EXECUTABLE} -c -uPER -o ${ASN_OUTPUT_DIR} ${_asn1cc_files}
    DEPENDS ${_asn1cc_files} ${ASN1CC_EXECUTABLE}
    COMMENT "Generating ASN.1 uPER codec using ASN1CC compiler"
    VERBATIM )

  set_source_files_properties(${${SRCS}} ${${HDRS}} PROPERTIES GENERATED TRUE)
  set(${SRCS} ${${SRCS}} PARENT_SCOPE)
  set(${HDRS} ${${HDRS}} PARENT_SCOPE)

endfunction()

#
# Main.
#

# Find the ASN1CC Executable
find_program(ASN1CC_EXECUTABLE
    NAMES asn1cc.exe Asn1f2.exe Asn1f4.exe
    DOC "The ASN1CC Compiler"
    PATHS
    ${ASN1CC_SRC_ROOT_FOLDER}/Asn1f4/bin/Debug/
    ${ASN1CC_SRC_ROOT_FOLDER}/Asn1f2/bin/Debug/
    ${ASN1CC_SRC_ROOT_FOLDER}/asn1cc/bin/Debug/
)
mark_as_advanced(ASN1CC_EXECUTABLE)
  
