#!/bin/sh

# Astyle pre-commit hook - Version 2.0 (By Ramon Fried and Yossi Segev)
# This file should be placed under .git/hooks and should have executables permissions
# Things to change (if you want):
# 1. The Astyle settings (it no longer takes it from the default)
# 2. The files the scripts operates upon (currently only C/C++ source / header files)

ASTYLE_SETTINGS_LINUX_USER_SPACE="--suffix=none \
                                    --style=allman \
                                    --indent=spaces=4 \
                                    --indent-classes \
                                    --indent-switches \
                                    --indent-cases \
                                    --indent-namespaces \
                                    --pad-oper \
                                    --pad-paren \
                                    --pad-header \
                                    --break-elseifs \
                                    --add-brackets \
                                    --align-pointer=name \
                                    --align-reference=name \
                                    --lineend=linux"

ASTYLE_SETTINGS_LINUX_KERNEL_SPACE="--style=1tbs \
                                    --indent=tab \
                                    --align-pointer=name \
                                    --add-brackets \
                                    --max-code-length=80"

ASTYLE_SETTINGS_GNU="--style=gnu \
                     --indent=spaces=2 \
                     --keep-one-line-blocks \
                     --add-brackets \
                     --max-code-length=120"

# Alter this line to change configuration
ASTYLE_PARAMETERS=${ASTYLE_SETTINGS_GNU}

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

ASTYLE=astyle

case `$ASTYLE --version 2> /dev/null` in
  Artistic*)
      ;;
  default)
      echo "Did not find astyle, please install it before continuing."
      exit 1
      ;;
esac

files=$(git-diff-index --diff-filter=ACMR --name-only -r --cached $against -- | grep -i '\.c$\|\.cpp$\|\.hpp$\|\.h$')

for file in $files; do
    x=`echo $file`
    if test "x$x" != "x"; then
	$ASTYLE ${ASTYLE_PARAMETERS} $file
        git add $file
    fi
done

